In [33]:
import numpy as np
import copy
import time
from helper_func import *
%load_ext autoreload

In [27]:
from multiprocessing import Process

def f(name):
    print('hello', name)

if __name__ == '__main__':
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()

hello bob


In [37]:
from multiprocessing import Pool

def f(x):
    return 55
t0 = time.time()
if __name__ == '__main__':
    with Pool(6) as p:
        print(p.map(f, [1,2,3,4,5,6,767,8,1, 2, 3]))
time.time() -t0

[55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55]


0.14136075973510742

In [35]:
def f(x):
    return 55
t0 = time.time()
for x in [1,2,3,4,5,6,767,8,1, 2, 3]:
    f(x)
time.time() - t0

6.699562072753906e-05

In [3]:

%autoreload 2

UsageError: Line magic function `%autoreload` not found.


In [23]:
test_state = np.array([[1,-1,1,0,0,0],[1,-1,1,0,0,0],[1,1,-1,0,0,0],[0,0,0,-1,-1,-1],[0,0,0,1,1,0],[0,0,0,-1,1,0]])
np.array2string(test_state.flatten(), max_line_width = 200)

'[ 1 -1  1  0  0  0  1 -1  1  0  0  0  1  1 -1  0  0  0  0  0  0 -1 -1 -1  0  0  0  1  1  0  0  0  0 -1  1  0]'

In [26]:
def boardstate_to_nn_input(boardstate):
    ''' returns a 72 length array with positions'''
    flat = copy.copy(test_state).flatten()
    flat1 = copy.copy(flat)
    flat1[flat1>0] = 0
    flat1[flat1<0] = 1
    flat[flat<0] = 0

    return np.concatenate([flat,flat1])
    
boardstate_to_nn_input(test_state)

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0])

In [96]:
boardstate_to_key(test_state)

update


'[121000121000113000000222000110000270]'

In [51]:
rotate_quadrant(test_state, 1, -1)

array([[ 1,  1,  1,  0,  0,  0],
       [ 1,  2, 44,  0,  0,  0],
       [ 3,  1, 55,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0],
       [ 0,  0,  0, 11, 12,  0],
       [ 0,  0,  0, 33, 17,  0]])

In [43]:
fullmove(test_state, (2,3), 100, 2, -1)

array([[  1,  44,  55, 100,   0,   0],
       [  1,   2,   1,   0,   0,   0],
       [  1,   1,   3,   0,   0,   0],
       [  0,   0,   0,  -1,  -1,   0],
       [  0,   0,   0,  11,  12,   0],
       [  0,   0,   0,  33,  17,   0]])

In [39]:
print(test_state)
print(test_state[(2,2)])
x = np.where(test_state == 0)
x = list(zip(x[0], x[1]))
x

[[ 1 44 55  0  0  0]
 [ 1  2  1  0  0  0]
 [ 1  1  3  0  0  0]
 [ 0  0  0 -1 -1  0]
 [ 0  0  0 11 12  0]
 [ 0  0  0 33 17  0]]
3


[(0, 3),
 (0, 4),
 (0, 5),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 5),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 5),
 (5, 0),
 (5, 1),
 (5, 2),
 (5, 5)]

In [4]:
place_marble(test_state, (2,3), -100)

array([[   1,   44,   55,    0,    0,    0],
       [   1,    2,    1,    0,    0,    0],
       [   1,    1,    3, -100,    0,    0],
       [   0,    0,    0,   -1,   -1,    0],
       [   0,    0,    0,   11,   12,    0],
       [   0,    0,    0,   33,   17,    0]])

In [88]:
for x in range(6):
    print(test_state[:,x])
print('each column')
for x in range(6):
    print(sum(test_state[x,:]))

[1 1 1 0 0 0]
[44  2  1  0  0  0]
[55  1  3  0  0  0]
[ 0  0  0 -1 11 33]
[ 0  0  0 -1 12 17]
[0 0 0 0 0 0]
each column
100
4
5
-2
23
50


In [142]:
test_state = np.array([[1,-1,1,0,0,0],[1,1,1,0,0,0],[1,1,-1,0,0,0],[0,0,0,-1,-1,1],[0,0,0,1,1,0],[0,0,0,-1,1,0]])
test_state

array([[ 1, -1,  1,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0],
       [ 1,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  1],
       [ 0,  0,  0,  1,  1,  0],
       [ 0,  0,  0, -1,  1,  0]])

In [102]:
def point_mass(input_mat):
    matrix_input = copy.copy(input_mat)
    matrix_input[matrix_input < 0] = 2
    print(matrix_input)
    y_column_positions = [matrix_input[:,x].dot(np.array([3,2,1,-1,-2,-3]))/sum(matrix_input[:,x]) if sum(matrix_input[:,x]) != 0 else 0 for x in range(6)]
    #y_column_masses = [sum(matrix_input[:,x]) for x in range(6)]
    print(y_column_positions)
    #x_position = np.dot(y_column_positions, np.array([-3,-2,-1,1,2,3]))/sum(y_column_positions)
    y_position = np.sum(y_column_positions)
    
    x_bar_positions = [matrix_input[x,:].dot(np.array([-3,-2,-1,1,2,3]))/sum(matrix_input[x,:]) if sum(matrix_input[x,:]) !=0 else 0 for x in range(matrix_input.shape[0])]
    print(x_bar_positions)
    x_position = np.sum(x_bar_positions)
    
    return x_position, y_position
print(point_mass(test_state))
#print(point_mass(np.rot90))

[[1 2 1 0 0 0]
 [1 2 1 0 0 0]
 [1 1 3 0 0 0]
 [0 0 0 2 2 2]
 [0 0 0 1 1 0]
 [0 0 0 2 7 0]]
[2.0, 2.2, 1.6, -2.0, -2.5, -1.0]
[-2.0, -2.0, -1.6, 2.0, 1.5, 1.7777777777777777]
(-0.32222222222222197, 0.3000000000000007)


In [143]:
def ideal_state(input_mat):
    matrix_input = copy.copy(input_mat)
    matrix_input[matrix_input < 0] = 2
    encoder_matrix = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])
    equivalent_matrices = []
    for x in [0,1,2,3]:
        rot_mat = np.rot90(matrix_input, x)
        equivalent_matrices.append(rot_mat)
        equivalent_matrices.append(np.fliplr(rot_mat))
        equivalent_matrices.append(np.flipud(rot_mat))
    
    encoded_scores = [np.dot(encoder_matrix.flatten(),equiv_matrix.flatten()) for equiv_matrix in equivalent_matrices]
    
    best_orientation = equivalent_matrices[encoded_scores.index(max(encoded_scores))]
    best_orientation[best_orientation == 2] = -1
    return best_orientation
    
    #print(encoder_matrix)                    
#    return np.dot(encoder_matrix.flatten(),matrix_input.flatten())
    

In [146]:
z = ideal_state(test_state)

In [148]:
for x in [0,1,2,3]:
    print(f"rotated {x} times.")
    rotated = np.rot90(test_state, x)
    print(rotated)
    #if ideal_state != z : print("ERRORRRR")
    print(ideal_state(rotated))
    print('')
    
    #l / r
    print("reflected along Y axis")
    lr = np.fliplr(rotated)
    print(lr)
    print(ideal_state(lr))
    print('')

    #u/d
    print("reflected along X axis")
    ud = np.flipud(rotated)
    print(ud)
    print(ideal_state(ud))
    
    print('_______________________________________')

rotated 0 times.
[[ 1 -1  1  0  0  0]
 [ 1  1  1  0  0  0]
 [ 1  1 -1  0  0  0]
 [ 0  0  0 -1 -1  1]
 [ 0  0  0  1  1  0]
 [ 0  0  0 -1  1  0]]
[[ 0  0  1  0  0  0]
 [ 1  1 -1  0  0  0]
 [-1  1 -1  0  0  0]
 [ 0  0  0 -1  1  1]
 [ 0  0  0  1  1 -1]
 [ 0  0  0  1  1  1]]

reflected along Y axis
[[ 0  0  0  1 -1  1]
 [ 0  0  0  1  1  1]
 [ 0  0  0 -1  1  1]
 [ 1 -1 -1  0  0  0]
 [ 0  1  1  0  0  0]
 [ 0  1 -1  0  0  0]]
[[ 0  0  1  0  0  0]
 [ 1  1 -1  0  0  0]
 [-1  1 -1  0  0  0]
 [ 0  0  0 -1  1  1]
 [ 0  0  0  1  1 -1]
 [ 0  0  0  1  1  1]]

reflected along X axis
[[ 0  0  0 -1  1  0]
 [ 0  0  0  1  1  0]
 [ 0  0  0 -1 -1  1]
 [ 1  1 -1  0  0  0]
 [ 1  1  1  0  0  0]
 [ 1 -1  1  0  0  0]]
[[ 0  0  1  0  0  0]
 [ 1  1 -1  0  0  0]
 [-1  1 -1  0  0  0]
 [ 0  0  0 -1  1  1]
 [ 0  0  0  1  1 -1]
 [ 0  0  0  1  1  1]]
_______________________________________
rotated 1 times.
[[ 0  0  0  1  0  0]
 [ 0  0  0 -1  1  1]
 [ 0  0  0 -1  1 -1]
 [ 1  1 -1  0  0  0]
 [-1  1  1  0  0  0]
 [ 1  1  1 

In [116]:
print(test_state)
ideal_state(test_state)

[[ 1 -1  1  0  0  0]
 [ 1  2  1  0  0  0]
 [ 1  1  3  0  0  0]
 [ 0  0  0 -1 -1  2]
 [ 0  0  0  1  1  0]
 [ 0  0  0 -3  7  0]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
620


In [102]:
np.fliplr(test_state)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [103]:
test_state = np.zeros((6,6))
test_state[2,3] = 1
test_state[3,3] = 1
test_state

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [103]:
for x in [0,1,2,3]:
    print(f"rotated {x} times.")
    rotated = np.rot90(test_state, x)
    #print(rotated)
    print(point_mass(rotated))
    print('')
    
    #l / r
    print("reflected along Y axis")
    lr = np.fliplr(rotated)
    #print(lr)
    print(point_mass(lr))
    print('')

    #u/d
    print("reflected along X axis")
    ud = np.flipud(rotated)
    #print(ud)
    print(point_mass(ud))
    
    print('_______________________________________')

rotated 0 times.
[[1 2 1 0 0 0]
 [1 2 1 0 0 0]
 [1 1 3 0 0 0]
 [0 0 0 2 2 2]
 [0 0 0 1 1 0]
 [0 0 0 2 7 0]]
[2.0, 2.2, 1.6, -2.0, -2.5, -1.0]
[-2.0, -2.0, -1.6, 2.0, 1.5, 1.7777777777777777]
(-0.32222222222222197, 0.3000000000000007)

reflected along Y axis
[[0 0 0 1 2 1]
 [0 0 0 1 2 1]
 [0 0 0 3 1 1]
 [2 2 2 0 0 0]
 [0 1 1 0 0 0]
 [0 7 2 0 0 0]]
[-1.0, -2.5, -2.0, 1.6, 2.2, 2.0]
[2.0, 2.0, 1.6, -2.0, -1.5, -1.7777777777777777]
(0.32222222222222197, 0.30000000000000027)

reflected along X axis
[[0 0 0 2 7 0]
 [0 0 0 1 1 0]
 [0 0 0 2 2 2]
 [1 1 3 0 0 0]
 [1 2 1 0 0 0]
 [1 2 1 0 0 0]]
[-2.0, -2.2, -1.6, 2.0, 2.5, 1.0]
[1.7777777777777777, 1.5, 2.0, -1.6, -2.0, -2.0]
(-0.3222222222222224, -0.3000000000000007)
_______________________________________
rotated 1 times.
[[0 0 0 2 0 0]
 [0 0 0 2 1 7]
 [0 0 0 2 1 2]
 [1 1 3 0 0 0]
 [2 2 1 0 0 0]
 [1 1 1 0 0 0]]
[-2.0, -2.0, -1.6, 2.0, 1.5, 1.7777777777777777]
[1.0, 2.5, 2.0, -1.6, -2.2, -2.0]
(-0.30000000000000027, -0.32222222222222197)

reflect

In [103]:
for x in [0,1,2,3]:
    print(f"rotated {x} times.")
    rotated = np.rot90(test_state, x)
    #print(rotated)
    print(point_mass(rotated))
    print('')
    
    #l / r
    print("reflected along Y axis")
    lr = np.fliplr(rotated)
    #print(lr)
    print(point_mass(lr))
    print('')

    #u/d
    print("reflected along X axis")
    ud = np.flipud(rotated)
    #print(ud)
    print(point_mass(ud))
    
    print('_______________________________________')

rotated 0 times.
[[1 2 1 0 0 0]
 [1 2 1 0 0 0]
 [1 1 3 0 0 0]
 [0 0 0 2 2 2]
 [0 0 0 1 1 0]
 [0 0 0 2 7 0]]
[2.0, 2.2, 1.6, -2.0, -2.5, -1.0]
[-2.0, -2.0, -1.6, 2.0, 1.5, 1.7777777777777777]
(-0.32222222222222197, 0.3000000000000007)

reflected along Y axis
[[0 0 0 1 2 1]
 [0 0 0 1 2 1]
 [0 0 0 3 1 1]
 [2 2 2 0 0 0]
 [0 1 1 0 0 0]
 [0 7 2 0 0 0]]
[-1.0, -2.5, -2.0, 1.6, 2.2, 2.0]
[2.0, 2.0, 1.6, -2.0, -1.5, -1.7777777777777777]
(0.32222222222222197, 0.30000000000000027)

reflected along X axis
[[0 0 0 2 7 0]
 [0 0 0 1 1 0]
 [0 0 0 2 2 2]
 [1 1 3 0 0 0]
 [1 2 1 0 0 0]
 [1 2 1 0 0 0]]
[-2.0, -2.2, -1.6, 2.0, 2.5, 1.0]
[1.7777777777777777, 1.5, 2.0, -1.6, -2.0, -2.0]
(-0.3222222222222224, -0.3000000000000007)
_______________________________________
rotated 1 times.
[[0 0 0 2 0 0]
 [0 0 0 2 1 7]
 [0 0 0 2 1 2]
 [1 1 3 0 0 0]
 [2 2 1 0 0 0]
 [1 1 1 0 0 0]]
[-2.0, -2.0, -1.6, 2.0, 1.5, 1.7777777777777777]
[1.0, 2.5, 2.0, -1.6, -2.2, -2.0]
(-0.30000000000000027, -0.32222222222222197)

reflect

In [5]:
def regularize_symmetry(matrix_input):
    best_rotation = 

SyntaxError: invalid syntax (<ipython-input-5-9f453d17e641>, line 2)

In [14]:
np.rot90(test_state)

array([[  0,   0,   0,  -1,  -1,  -3],
       [  0,   0,   0,  -1,  -2, -17],
       [  0,   0,   0,  -1,  -1,  -1],
       [ 55,   1,   3,   0,   0,   0],
       [  1,   2,   1,   0,   0,   0],
       [  1,   1,   1,   0,   0,   0]])

In [15]:
np.rot90(test_state, 2)

array([[ -3, -17,  -1,   0,   0,   0],
       [ -1,  -2,  -1,   0,   0,   0],
       [ -1,  -1,  -1,   0,   0,   0],
       [  0,   0,   0,   3,   1,   1],
       [  0,   0,   0,   1,   2,   1],
       [  0,   0,   0,  55,   1,   1]])

In [16]:
np.rot90(test_state, 3)

array([[  0,   0,   0,   1,   1,   1],
       [  0,   0,   0,   1,   2,   1],
       [  0,   0,   0,   3,   1,  55],
       [ -1,  -1,  -1,   0,   0,   0],
       [-17,  -2,  -1,   0,   0,   0],
       [ -3,  -1,  -1,   0,   0,   0]])

In [18]:
test_state

array([[  1,   1,  55,   0,   0,   0],
       [  1,   2,   1,   0,   0,   0],
       [  1,   1,   3,   0,   0,   0],
       [  0,   0,   0,  -1,  -1,  -1],
       [  0,   0,   0,  -1,  -2,  -1],
       [  0,   0,   0,  -1, -17,  -3]])

In [19]:
np.flipud(np.fliplr(test_state))

array([[ -3, -17,  -1,   0,   0,   0],
       [ -1,  -2,  -1,   0,   0,   0],
       [ -1,  -1,  -1,   0,   0,   0],
       [  0,   0,   0,   3,   1,   1],
       [  0,   0,   0,   1,   2,   1],
       [  0,   0,   0,  55,   1,   1]])

In [9]:
np.rot90(np.fliplr(test_state)

array([[  0,   0,   0,  55,   1,   1],
       [  0,   0,   0,   1,   2,   1],
       [  0,   0,   0,   3,   1,   1],
       [ -1,  -1,  -1,   0,   0,   0],
       [ -1,  -2,  -1,   0,   0,   0],
       [ -3, -17,  -1,   0,   0,   0]])

In [10]:
np.flipud(test_state)

array([[  0,   0,   0,  -1, -17,  -3],
       [  0,   0,   0,  -1,  -2,  -1],
       [  0,   0,   0,  -1,  -1,  -1],
       [  1,   1,   3,   0,   0,   0],
       [  1,   2,   1,   0,   0,   0],
       [  1,   1,  55,   0,   0,   0]])

In [12]:
xx = np.array([1,0,1,0,0,1])
print(xx*np.array([3,2,1,-1,-2,-3]))
xx.dot(np.array([3,2,1,-1,-2,-3]))

[ 3  0  1  0  0 -3]


1

# update q table algo:

In [3]:
test_state[:,1:]

array([[ 1,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 0,  0, -1, -1, -1],
       [ 0,  0, -1, -1, -1],
       [ 0,  0, -1, -1, -1]])

In [68]:
test_state = np.array([[1,1,1,0,0,0],[1,1,1,1,1,0],[1,1,1,0,0,0],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1]])
print(test_state)
def find_winner(board_state):
    white_win = False
    black_win = False
    diagnol1 = board_state.diagonal()
    diagnol2 = np.fliplr(board_state).diagonal()
    winning_slices =  np.vstack([board_state[1:,:].T, board_state[:-1,:].T, # all columns
                          board_state[:,1:], board_state[:,:-1], # all rows
                          diagnol1[1:], diagnol1[:-1], # diagnol 1
                          diagnol2[1:],diagnol2[1:]]) # diagnol 2
    print(winning_slices)
    sums = np.dot(winning_slices, np.array([1,1,1,1,1]))
    print(sums)
    if 5 in sums: white_win = True
    if -5 in sums: black_win = True
    print(white_win, black_win)
find_winner(test_state)

[[ 1  1  1  0  0  0]
 [ 1  1  1  1  1  0]
 [ 1  1  1  0  0  0]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]]
[[ 1  1  0  0  0]
 [ 1  1  0  0  0]
 [ 1  1  0  0  0]
 [ 1  0 -1 -1 -1]
 [ 1  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 1  1  1  0  0]
 [ 1  1  1  0  0]
 [ 1  1  1  0  0]
 [ 0  1  0 -1 -1]
 [ 0  1  0 -1 -1]
 [ 0  0  0 -1 -1]
 [ 1  1  0  0  0]
 [ 1  1  1  1  0]
 [ 1  1  0  0  0]
 [ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 1  1  1  0  0]
 [ 1  1  1  1  1]
 [ 1  1  1  0  0]
 [ 0  0  0 -1 -1]
 [ 0  0  0 -1 -1]
 [ 0  0  0 -1 -1]
 [ 1  1 -1 -1 -1]
 [ 1  1  1 -1 -1]
 [ 1  0  0  0  0]
 [ 1  0  0  0  0]]
[ 2  2  2 -2 -2 -3  3  3  3 -1 -1 -2  2  4  2 -3 -3 -3  3  5  3 -2 -2 -2
 -1  1  1  1]
True False


In [58]:
test_state.diagonal()[1:].reshape(1,)

ValueError: cannot reshape array of size 5 into shape (1,)