## Final Project Pentago

### Play Game

In [109]:
import numpy as np
import random
from datetime import datetime
from collections import defaultdict
from helper_func import *
%load_ext autoreload


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [110]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [159]:
### Apologies for the janky version control. This cell is the 'unified' pentago class per last night's meeting. Once we're happy here, we can delete the cells below this.

class pentago:
    """
    
    """

    def __init__(self, state = None):
        """Initializes the class reservation"""
        print('initializing')
        print(state)
        if state == None:
            self.state = state = np.zeros((6,6), dtype=np.int)
        self.history = []
        self.winner = None
        self.gameover = False
        self.player_turn = 1
    
    def current_board_state(self):
        #self.state = state
        #print("The current board state is: ", self.state)
        return copy.copy(self.state)

    def start_date(self):
        y = time
        self.game_time = y
        return game_time
    
    def game_history(self, player, move, cuad, rotatation):
        self.history.append((boardstate_to_ideal_key(self.state), player, move, cuad, rotatation))
        #return self.history
        
    def place(self, locate=None, marbel=None):
        """
        locate: is a tuple (x,y) with the position in the board
                x is the horizontal coordinate (0-5)
                y is the vertical coordinate (0-5)
        """
        self.locate = locate
        self.marbel = marbel
        
        if self.locate == None:
            print('No location Added')
        elif self.locate[0] > 5 or self.locate[0] < 0 or self.locate[1] > 5 or self.locate[1] < 0:
            print('Out of Board')
        else:
            x = self.locate[0]
            y = self.locate[1]
            if(self.state[x,y] == 0):
                self.state[x,y] = self.marbel
                return 1
            else:
                print('Error!! Position taken. Please select another position.')
                return None

                
    def rotate(self, cuad= None, orient=None):
        """
        Cuad: Select cuadrant.
              If 1, topleft
              if 2, top right
              if 3, bottom left
              if 4, bottom right
        orient: Select orientation
                if 1, clockwise
                if -1, counterclockwise
        """
        self.cuad = cuad
        self.orient = orient
        
        mr = np.zeros((3,3), dtype=np.int)
        if cuad == 1:
            c1 = (0,3)
            c2 = (0,3)
        elif cuad == 2:
            c1 = (0,3)
            c2 = (3,6)
        elif cuad == 3:
            c1 = (3,6)
            c2 = (0,3)
        elif cuad == 4:
            c1 = (3,6)
            c2 = (3,6)

        mr = self.state[c1[0]:c1[1],c2[0]:c2[1]]
        if orient == 1:
            mr = np.array(list(zip(*mr[::-1])))
        elif orient == -1:
            mr = np.array(list(zip(*mr[:,::-1])))
            
        self.state[c1[0]:c1[1],c2[0]:c2[1]] = mr      
        print('rotation completed.')  

    def find_winner(self, board_state):
        player1_win = False
        player_min1_win = False
        diagonal1 = board_state.diagonal()
        diagonal2 = np.fliplr(board_state).diagonal()
        winning_slices =  np.vstack([board_state[1:,:].T, board_state[:-1,:].T, # all columns
                              board_state[:,1:], board_state[:,:-1], # all rows
                              diagonal1[1:], diagonal1[:-1], # diagonal 1
                              diagonal2[1:],diagonal2[1:], # diagonal 2
                              board_state.diagonal(offset=1), board_state.diagonal(offset=-1), # diagonal offsets 
                              np.fliplr(board_state).diagonal(offset=1), np.fliplr(board_state).diagonal(offset=-1)] ) # diagonal offsets
        sums = np.dot(winning_slices, np.array([1,1,1,1,1]))
        if 5 in sums: player1_win = True
        if -5 in sums: player_min1_win = True
        if player1_win == True or player_min1_win == True:
            print("Player 1 winner?", player1_win, "Player -1 marble winner?", player_min1_win)
            self.gameover = True
            if player1_win == True:
                self.winner = 1
            elif player_min1_win ==True:
                self.winner = 0
            self.history.append(self.winner)
        return "Win"

    def check_gameover(self):
        if not 0 in self.state:
              self.gameover = True
              print("The game board is full!")
        
    def full_move(self, move, cuad, direction, player, dtype=np.int):
        if player != self.player_turn:
            print( "error, wrong player turn. No move taken.")
            return 'Error, wrong player turn.'
        if self.place(move, player) == None:
          return 'Error, place already taken'# maybe returns here if illegal move <-- Part of place method
        self.rotate(cuad, direction)
        self.game_history(move, player, cuad, direction)
        self.find_winner(self.state) #return in find_winner if a winner is found
        self.check_gameover() #return in check_gameover
        if player == 1:
            self.player_turn = -1
        else:
            self.player_turn = 1
        print('Successful Move')
        return self.state




In [112]:
x = pentago()
print(x.current_board_state())

initializing
None
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [113]:
#Testing basic functionality
p = pentago()
print(p.state)
p.full_move((1,2),1,1,1)
print(p.state)
p.full_move((1,5),2,1,-1)
print(p.state)
p.full_move((5,2),3,1,1)
print(p.state)
p.full_move((5,5),2,1,-1)
print(p.state)
p.full_move((1,2),3,1,1)
print(p.state)
p.full_move((1,2),4,1,-1)
p.history

initializing
None
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
rotation completed.
Successful Move
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
rotation completed.
Successful Move
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
rotation completed.
Successful Move
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]]
rotation completed.
Successful Move
[[ 0  0  0  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 1  0  0  0  0 -1]]
rotation completed.
Successful Move
[[ 0  0  0  0  0  0]
 [ 0  0  1 -1  0  0]
 [ 0  1  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0 -1]]
Error!! Position taken. Please select another position.


[(array([[ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  1, -1,  0,  0],
         [ 0,  1,  0,  0,  0,  0],
         [ 1,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0, -1]]),
  (1, 2),
  1,
  1,
  1),
 (array([[ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  1, -1,  0,  0],
         [ 0,  1,  0,  0,  0,  0],
         [ 1,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0, -1]]),
  (1, 5),
  -1,
  2,
  1),
 (array([[ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  1, -1,  0,  0],
         [ 0,  1,  0,  0,  0,  0],
         [ 1,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0, -1]]),
  (5, 2),
  1,
  3,
  1),
 (array([[ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  1, -1,  0,  0],
         [ 0,  1,  0,  0,  0,  0],
         [ 1,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0, -1]]),
  (5, 5),
  -1,
  2,
  1),
 (array([[ 0,  0,  0,  0,  0,  0],
         [ 

In [114]:
p.current_board_state()

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, -1,  0,  0],
       [ 0,  1,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1]])

In [179]:

class q_table:

    def __init__(self,length=0, games_played=0):
        """Initializes the class reservation"""
        self.time = datetime.now()
        self.length = length
        self.q_dict = {}
        self.games_played = games_played

  #def time(self):
    #self.time = time

    def length(self):
        self.length += 1
    #self.length = length  
    
    def get_q_value(self, boardstate):
        return self.q_dict.get(boardstate, (.5, 0))
    
    def update_q_value(self, boardstate, new_val, update_function = None):
        q_val, n = self.get_q_value(boardstate) 
        if update_function:
            print('using custom function')
            self.q_dict[boardstate] = update_function(q_val, n, new_val)
        else:
            self.q_dict[boardstate] = [new_val, n+1]
        return self.q_dict[boardstate]
    
    def update_post_game(self, history, update_fn):
        winner = history[-1]
        
        for boardposition in history[-2::-1]:
            key = boardposition[0]
            print(key, winner)
            self.update_q_value(key, winner, update_fn)
    
    
    
    

In [178]:
for x in game_trial.history[-2::-1]:
    print(x)
    print('')

('[202211100111122222101022212211221111]', (0, 3), 1, 3, 1)

('[211022002012202121222021111211211211]', (3, 0), -1, 2, -1)

('[211100002212202122022021111211211211]', (4, 5), 1, 2, 1)

('[202012100211122211001022212211221101]', (5, 3), -1, 1, 1)

('[211011111210022021202121100012122022]', (2, 5), 1, 1, -1)

('[211011111210022021202120002012211022]', (4, 3), -1, 4, 1)

('[020112110111101220021202210200220112]', (4, 1), 1, 1, -1)

('[020112110101101220021122210100220202]', (3, 0), -1, 3, -1)

('[112020102011010101221120001012202022]', (3, 5), 1, 3, 1)

('[011020101011022100221120001012202022]', (2, 4), -1, 2, -1)

('[020110110101001220200122212100001202]', (4, 2), 1, 2, -1)

('[020110110001001220022122010100120202]', (2, 0), -1, 1, 1)

('[011020100011022100002220002010211021]', (4, 4), 1, 3, -1)

('[020201100201001010022200010200120112]', (2, 3), -1, 1, 1)

('[010001200212001000220002001002110211]', (3, 3), 1, 2, 1)

('[010020200010000021220002001002110211]', (0, 2), -1, 4, 1)

('[020020

In [174]:
def my_func(q, n, nn):
    #print('here',q, n, nn, 'end')
    #q, n = cv
    return (q*n+nn)/(n+1), n+1

x = q_table()
print(x.get_q_value('sdfsd'))
#x.q_dict['sdfsd']
x.update_q_value('sdfsd', 4, my_func)
x.update_q_value('sdfsd', 1, my_func)

(0.5, 0)
using custom function
using custom function


(2.5, 2)

In [190]:
def dampen_func(q, n, nn):
    print('here',q, n, nn, 'end')
    #q, n = cv
    return (q*(n+1)+nn)/(n+2), n+1

x = q_table()
print(x.get_q_value('sdfsd'))
#x.q_dict['sdfsd']
x.update_q_value('sdfsd', 4, my_func)
x.update_q_value('sdfsd', 1, my_func)

(0.5, 0)
using custom function
using custom function


(2.5, 2)

In [195]:
#qq = q_table()
qq.update_post_game(game_trial.history, dampen_func)

[202211100111122222101022212211221111] 0
using custom function
here 0.25 1 0 end
[211022002012202121222021111211211211] 0
using custom function
here 0.25 1 0 end
[211100002212202122022021111211211211] 0
using custom function
here 0.25 1 0 end
[202012100211122211001022212211221101] 0
using custom function
here 0.25 1 0 end
[211011111210022021202121100012122022] 0
using custom function
here 0.25 1 0 end
[211011111210022021202120002012211022] 0
using custom function
here 0.25 1 0 end
[020112110111101220021202210200220112] 0
using custom function
here 0.25 1 0 end
[020112110101101220021122210100220202] 0
using custom function
here 0.25 1 0 end
[112020102011010101221120001012202022] 0
using custom function
here 0.25 1 0 end
[011020101011022100221120001012202022] 0
using custom function
here 0.25 1 0 end
[020110110101001220200122212100001202] 0
using custom function
here 0.25 1 0 end
[020110110001001220022122010100120202] 0
using custom function
here 0.25 1 0 end
[011020100011022100002220002

In [196]:
qq.q_dict

{'[202211100111122222101022212211221111]': (0.16666666666666666, 2),
 '[211022002012202121222021111211211211]': (0.16666666666666666, 2),
 '[211100002212202122022021111211211211]': (0.16666666666666666, 2),
 '[202012100211122211001022212211221101]': (0.16666666666666666, 2),
 '[211011111210022021202121100012122022]': (0.16666666666666666, 2),
 '[211011111210022021202120002012211022]': (0.16666666666666666, 2),
 '[020112110111101220021202210200220112]': (0.16666666666666666, 2),
 '[020112110101101220021122210100220202]': (0.16666666666666666, 2),
 '[112020102011010101221120001012202022]': (0.16666666666666666, 2),
 '[011020101011022100221120001012202022]': (0.16666666666666666, 2),
 '[020110110101001220200122212100001202]': (0.16666666666666666, 2),
 '[020110110001001220022122010100120202]': (0.16666666666666666, 2),
 '[011020100011022100002220002010211021]': (0.16666666666666666, 2),
 '[020201100201001010022200010200120112]': (0.16666666666666666, 2),
 '[0100012002120010002200020010021

In [117]:

class q_table:

  def __init__(self,length=0, games_played=0, q_dict={}):
        """Initializes the class reservation"""
        self.time = datetime.now()
        self.length = length
        self.q_dict = defaultdict([.5,0])
        self.games_played = games_played

  #def time(self):
    #self.time = time

  def length(self):
    self.length += 1
    #self.length = length    

  def q_dict_update(self, game_board):
    """
    Have to make sure that the q_dict survives from game to game so that it
    captures all of the board states, q_values, and iterations. This will
    have to be done in concert with the backprop function since it is a 
    recursive action.
    """
    #Grabs current board state, turns it into a string
    

    ###########
    # joe's default dict idea
#    for gb in history:
#      cv = self.q_dict[str(flatten(gb))]
#      nv = do the back prop 
#          { assign winning board = 1/0
#            average (c_q_value*n + 1/0 * dampener towards .5 )n+1}
#      self.q_dict[str(flatten(gb))] = nv
#    q_dict = 


    ############



    #Checks keys in the dictionary to see if it currently exists
    key_list = []
    for n in self.q_dict.keys(): 
      key_list.append(n)

    if g in key_list:
      #Update q value, update n_counter
      self.q_dict[g][0] += x ##This is where the backprop from Joe's function will feed
      self.q_dict[g][1] += 1
        else:
      #Add to dictionary, default q value to 0.5, Update n_counter
      self.q_dict[g] = [0.5, 1]
    
    def q_value_returner(gb or list of gb):
        return self.q_dict[gb]

    def games_played(self):
        games_played += 1
        self.games_played = games_played

IndentationError: unexpected indent (<ipython-input-117-ea467d666cde>, line 51)

In [93]:
x = defaultdict(list)
x['zoom'].append('11')
x['test'].append('22')
x['rrrr'].append(44)
x['teset'].append((3,4,5,4))
random.choice(list(x.keys()))

'teset'

In [120]:
%autoreload 2
class qtable_agent:
    
    def __init__(self, player = 1, epsilon = 1, epsilon_decay = .995, q_table = q_table()):
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.q_table = q_table
        self.player = player
        
            
    def get_avail_moves(self,boardstate):
        """
        This method creates a list with available spaces in the board and combination of quadrant and rotation
        The input is the board state (6x6) numpy array
        """
        x = np.where(boardstate == 0)
        #print(x)
        available_positions_for_placement = list(zip(x[0], x[1]))
        
        # all available positions (p), quadrants(q), rotations(r)
        available_moves = [(p,q,r) for p in available_positions_for_placement for q in [1,2,3,4] for r in [-1,1]]
        #print(len(available_moves))
        return available_moves
    
    def get_possible_next_boardstates(self, boardstate):
        next_possible_boardstates = defaultdict(list)
        for move in self.get_avail_moves(boardstate):
            possible_boardstate = fullmove(boardstate,*move, self.player)
            key = boardstate_to_ideal_key(possible_boardstate)
            #print(key)
            next_possible_boardstates[key].append(move)
            
        return next_possible_boardstates
    
    def make_move(self, game):
        
        # get the current boardstate from the pentago class
        boardstate = game.current_board_state()
        
        # get possible next possible boardstates
        next_possible_boardstates = self.get_possible_next_boardstates(boardstate)
        key_list = list(next_possible_boardstates.keys())
        
        # determine if to take random move
        if np.random.rand() < self.epsilon:
            random_bs = random.choice(key_list)
            random_mv = next_possible_boardstates[random_bs][0]
            
            game.full_move(*random_mv,self.player)
            
        else:
            print("not random")
            q_values_list = [self.q_table.get_q_value(bs) for bs in key_list]
            print(q_values_list)
            index_of_best_move = q_values_list.index(max(q_values_list))
            
            ## list all max q_values and choose at random
            mv_to_take = next_possible_boardstates[key_list[index_of_best_move]][0]
            game.full_move(*mv_to_take, self.player)
            
        self.epsilon *= self.epsilon_decay 

In [69]:
q_table1 = q_table()
q_table1.get_q_value('test')

(0.5, 0)

In [60]:
agent = qtable_agent()
#agent.get_avail_moves(p.current_board_state())
#agent.get_possible_next_boardstates(np.zeros((6,6), dtype=np.int))
agent.make_move(p)

error, wrong player turn. No move taken.


In [166]:
agent1 = qtable_agent()
agent2 = qtable_agent(player = -1)
game_trial = pentago()

while game_trial.gameover == False:
        agent1.make_move(game_trial)
        print(game_trial.current_board_state())
        
        if game_trial.gameover == True:
            break
        
        agent2.make_move(game_trial)
#        print(game_trial.current_board_state())

game_trial.history

initializing
None
rotation completed.
Successful Move
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
rotation completed.
Successful Move
rotation completed.
Successful Move
[[ 0 -1  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
rotation completed.
Successful Move
rotation completed.
Successful Move
[[ 0  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [ 1  1 -1  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  0  0]]
rotation completed.
Successful Move
rotation completed.
Successful Move
[[ 1 -1  0  0  0  0]
 [ 1  0  0  0  0  0]
 [-1  0  0  0  0  0]
 [ 0  1  0  0 -1  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  0  0]]
rotation completed.
Successful Move
rotation completed.
Successful Move
[[ 1 -1  0  0  0  0]
 [ 1  0  0  0  1  0]
 [-1  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  1]
 [-1  0  0  0 -1  0]]
rotation completed.
Successful Move
rotation completed.
Suc

[('[000000000000000000000000000000000010]', (0, 1), 1, 1, -1),
 ('[000000000000000000000000000001000020]', (0, 1), -1, 2, -1),
 ('[000000000000010000000000000001000020]', (4, 3), 1, 4, 1),
 ('[000000001000000000000200000100000020]', (2, 0), -1, 1, -1),
 ('[000000000000010000000200000100000120]', (2, 0), 1, 4, -1),
 ('[000000002000010000000000000002000211]', (3, 4), -1, 1, 1),
 ('[000000002000010000000000001002000211]', (3, 1), 1, 2, -1),
 ('[020000001000000000000000001002200211]', (5, 0), -1, 4, 1),
 ('[000010010002000000000000200100112002]', (1, 4), 1, 4, 1),
 ('[000020010100000000000000200102112002]', (5, 1), -1, 4, -1),
 ('[000020010100100000002000001102021002]', (0, 3), 1, 1, -1),
 ('[000020012100001000002000001102021002]', (1, 3), -1, 2, -1),
 ('[000000010002021211010010200201000200]', (4, 2), 1, 3, -1),
 ('[020000001212000100220000001002010211]', (0, 4), -1, 1, 1),
 ('[020020001010000021220000001002110211]', (5, 0), 1, 2, 1),
 ('[010020200010000021220002001002110211]', (0, 2), -1

In [223]:
def Simulate_Game(agent1, agent2, updater):
        print('yes')

In [105]:
#  neural network input (boardstate)> 6x6x2 > q_value
# when choosing 
#
#
#

In [159]:
## initial code from Ernesto

class agent:
    
    def __init__(self):
        self.action = None
        self.av = []
        self.new_state = np.zeros((6,6), dtype=np.int)
      
    def avail(self,state):
        """
        This method creates a list with available spaces in the board
        The input is the board state (6x6) numpy array
        """
        for i in range(6):
            for j in range(6):
                if state[i,j]==0:
                    self.av.append((i,j))
                    
    def play(self, state,q_indic, eps = 1.0, mbl = 1):
        """
        play method place a marbel by an imput state of the board
        q_indic is the dictionary with q values in the followinf format:
        {board code (string): q value (float)}, For example:
        {'212201122201222112201022110121120022': 0.65}
        eps: is epasilon. It is the threshold to ramdomly determine to
             make a random move or play by q values
        mbl: 1 or 2. the marbel playing.
        
        """
        
        def mat2str(m):
            """Board matrix to string code"""
            v = m.flatten()
            st = ''
            for k in v:
                st += str(k)
            return st
        
        def str2mat(code):
            """String code to matrix"""
            v = [int(k) for k in code]
            npv = np.array(v)
            return npv.reshape(6,6)
        
        #Start a petago object to analize the moves
        test_table = pentago(np.zeros((6,6), dtype=np.int))
        
        if eps > random.uniform(0,1): # Play random
            xy = self.av[random.randint(0,len(self.av)-1)] #Select from availables spots 
            c = random.randint(1,4)
            r = random.choice([-1, 1])                                     
            self.action = (xy, mbl, c, r)
            test_table.state = state.copy() # Copy the board state
            test_table.full_move(xy,mbl,c, r) # Full Move
            self.new_state = test_table.state
            
        else:# Play acording to q values
            act_dic = {}
            q_dic = {}
            
            #Creating the states after all possible move and creaste 2 dictionaries
            #with resultant states codes, actions and qvalues 
            for k in self.av:
                for j in range(1,5):
                    for i in [-1,1]: 
                        test_table.state = state.copy()                        
                        test_table.full_move(k,mbl,j,i)
                        state_code = mat2str(test_table.state)
                        try:
                            q_dic[state_code] = q_indic[state_code]     
                            act_dic[state_code] = (k,mbl,j,i)
                        except:
                            pass
            
            #If q values are found, select the maximum value
            #If more than one qvalue is maximum, pick one randomly
            if len(act_dic) > 0:
                max_value = max(q_dic.values())
                [k for k,v in q_dic.items() if v == max_value]
                code = random.choice(k)
                self.action = act_dic[code]
                self.new_state = str2mat(code)
                
            #If no qvalue is found, play randomly
            else:
                xy = self.av[random.randint(0,len(self.av)-1)]
                c = random.randint(1,4)
                r = random.choice([-1, 1])                                     
                self.action = (xy, mbl, c, r)
                test_table.state = state.copy()
                test_table.full_move(xy,mbl,c, r)
                self.new_state = test_table.state

In [ ]:
l ={'a':[1,2], 'b':[2,3], 'm':[29,1]}
keyz = []
for n in l.keys():
  keyz.append(n)
l['m'][0]

29

In [ ]:
agent1
{ call for current board state,
  put that into intelligence (neural network, q table, random, heuristic, simulation tree (graph theory), etc)
  returns best move > full_move(...)}

In [ ]:
# class pentago:
#     """
    
#     """

#     def __init__(self,state= np.zeros((6,6), dtype=np.int)):
#         """Initializes the class reservation"""
#         self.state = state
#         self.history = []
#         self.winner = None
#         self.gameover = False
    
#     def current_board_state(self):
#         #self.state = state
#         print("The current board state is: ", self.state)

#     def start_date(self):
#         y = time
#         self.game_time = y
#         return game_time
    
#     def game_history(self, (x,y), cuad, rotatation):
#         self.history.append((self.state,(x,y), cuad, rotatation))
#         #return self.history
        
#     def place(self, locate=None, marbel=None):
#         """
#         locate: is a tuple (x,y) with the position in the board
#                 x is the horizontal coordinate (0-5)
#                 y is the vertical coordinate (0-5)
#         """
#         self.locate = locate
#         self.marbel = marbel
        
#         if self.locate == None:
#             print('No location Added')
#         elif self.locate[0] > 5 or self.locate[0] < 0 or self.locate[1] > 5 or self.locate[1] < 0:
#             print('Out of Board')
#         else:
#             x = self.locate[0]
#             y = self.locate[1]
#             if(self.state[x,y] == 0):
#                 self.state[x,y] = self.marbel
#             else:
#                 print('Position taken')
#                 ## add return of error
                
#     def rotate(self, cuad= None, orient=None):
#         """
#         Cuad: Select cuadrant.
#               If 1, topleft
#               if 2, top right
#               if 3, bottom left
#               if 4, bottom right
#         orient: Select orientation
#                 if 1, clockwise
#                 if -1, counterclockwise
#         """
#         self.cuad = cuad
#         self.orient = orient
        
#         mr = np.zeros((3,3), dtype=np.int)
#         if cuad == 1:
#             c1 = (0,3)
#             c2 = (0,3)
#         elif cuad == 2:
#             c1 = (0,3)
#             c2 = (3,6)
#         elif cuad == 3:
#             c1 = (3,6)
#             c2 = (0,3)
#         elif cuad == 4:
#             c1 = (3,6)
#             c2 = (3,6)

#         mr = self.state[c1[0]:c1[1],c2[0]:c2[1]]
#         if orient == 1:
#             mr = np.array(list(zip(*mr[::-1])))
#         elif orient == -1:
#             mr = np.array(list(zip(*mr[:,::-1])))
            
#         self.state[c1[0]:c1[1],c2[0]:c2[1]] = mr        


#         #def check_gameover(self):
#         #  if not 0 in self.state:
#         #    return 'gameover'
        
#         #def full_move(self, ....):
#         #  place(). # maybe returns here if illegal move
#         #  rotate()
#         #  self.history()
#         #  check_for_win(). -- return something if win
#         #  check_gameover(). -- return something if gameover
#         #  return self.state

In [ ]:
behavioral_analysis_agent():
  game.history. > neural network that is trained 

In [ ]:
p = pentago()

In [ ]:
p.current_board_state()

The current board state is:  [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
test_state = np.array([[1,1,1,1,1,0],[1,-1,1,1,1,0],[1,1,-1,0,0,0],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1]])
0 in test_state

True

In [ ]:
# this cell has an algo to determine if a winning state has been reached
test_state = np.array([[1,1,1,1,1,0],[1,-1,1,1,1,0],[1,1,-1,0,0,0],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1],[0,0,0,-1,-1,-1]])
print(test_state)
def find_winner(board_state):
    white_win = False
    black_win = False
    diagonal1 = board_state.diagonal()
    diagonal2 = np.fliplr(board_state).diagonal()
    winning_slices =  np.vstack([board_state[1:,:].T, board_state[:-1,:].T, # all columns
                          board_state[:,1:], board_state[:,:-1], # all rows
                          diagonal1[1:], diagonal1[:-1], # diagonal 1
                          diagonal2[1:],diagonal2[1:], # diagonal 2
                          board_state.diagonal(offset=1), board_state.diagonal(offset=-1), # diagonal offsets 
                          np.fliplr(board_state).diagonal(offset=1), np.fliplr(board_state).diagonal(offset=-1)] ) # diagonal offsets
                
    print(winning_slices)
    sums = np.dot(winning_slices, np.array([1,1,1,1,1]))
    print(sums)
    if 5 in sums: white_win = True
    if -5 in sums: black_win = True
    print(white_win, black_win)
find_winner(test_state)

[[ 1  1  1  1  1  0]
 [ 1 -1  1  1  1  0]
 [ 1  1 -1  0  0  0]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]]
[[ 1  1  0  0  0]
 [-1  1  0  0  0]
 [ 1 -1  0  0  0]
 [ 1  0 -1 -1 -1]
 [ 1  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 1  1  1  0  0]
 [ 1 -1  1  0  0]
 [ 1  1 -1  0  0]
 [ 1  1  0 -1 -1]
 [ 1  1  0 -1 -1]
 [ 0  0  0 -1 -1]
 [ 1  1  1  1  0]
 [-1  1  1  1  0]
 [ 1 -1  0  0  0]
 [ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 0  0 -1 -1 -1]
 [ 1  1  1  1  1]
 [ 1 -1  1  1  1]
 [ 1  1 -1  0  0]
 [ 0  0  0 -1 -1]
 [ 0  0  0 -1 -1]
 [ 0  0  0 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 1 -1 -1 -1 -1]
 [ 1  0  0  0  0]
 [ 1  0  0  0  0]
 [ 1  1  0 -1 -1]
 [ 1  1  0 -1 -1]
 [ 1  1 -1  0  0]
 [ 0  0 -1  0  0]]
[ 2  0  0 -2 -2 -3  3  1  1  0  0 -2  4  2  0 -3 -3 -3  5  3  1 -2 -2 -2
 -5 -3  1  1  0  0  1 -1]
True True


In [ ]:
x,y,cuad,rotation,marble

In [ ]:
class play_pentago(object):
    def run(self):
        
        table = pentago(np.zeros((6,6), dtype=np.int))
        mb=1
        cuadrants = [1,2,3,4]
        rotation = [-1,1]
        av = [(i,j) for i in range(6) for j in range(6)]
        
        cont = 1
        while av != []:
            
            random.shuffle(av) 
            xy = av.pop()
            
            table.place(xy,mb)            
            print(table.state,'Marbel Placed','\n')

            random.shuffle(cuadrants) 
            random.shuffle(rotation)
            table.rotate(cuadrants[0],rotation[0])
            print(table.state,'Rotation','\n')
            print('Play: {}, Marbel: {}, Placed: {}, Cuadrant: {}, Rotated: {}\n'
                  .format(cont,mb,xy,cuadrants[0],rotation[0]))
            
            mb = -mb # Switching player
            
            av = [] # Available list
            for i in range(6):
                for j in range(6):
                    if table.state[i,j]==0:
                        av.append((i,j))
                        
            cont += 1
        return #Main program

In [ ]:
if __name__ == '__main__': #Run main interface with user
    output = play_pentago().run()

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] Marbel Placed 

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] Rotation 

Play: 1, Marbel: 1, Placed: (1, 0), Cuadrant: 2, Rotated: -1

[[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]] Marbel Placed 

[[ 0  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]] Rotation 

Play: 2, Marbel: -1, Placed: (2, 4), Cuadrant: 3, Rotated: 1

[[ 0  0  0  1  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]] Marbel Placed 

[[ 0  1  0  1  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 -1  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]] Rotation 

Play: 3, Marbel: 1, Placed: (0, 3), Cuadrant: 1, Rotated: 1

[[ 0  1  0  1  0  0]
 [ 0  0  0  0  0  0]
 [